### ISSUE TITLE
dh-python doesn't have /usr/bin/pybuild 

### ISSUE THREAD

**Issue by sergiomb2** [UnitedRPMs/dh-python#1]
```
dget http://deb.debian.org/debian/pool/main/p/python-html2text/python-html2text_2018.1.9-1.dsc 
cd python-html2text-2018.1.9
dpkg-buildpackage -d
```

ends with Can't exec "pybuild": No such file or directory at /usr/share/perl5/vendor_perl/Debian/Debhelper/Dh_Lib.pm line 471.

**Comment by kuboosoft** [comment]
@sergiomb2 Can you test the update? Thanks

**Comment by sergiomb2** [comment]
Works much better , I want include this package on Fedora proper

**Comment by sergiomb2** [comment]
Works much better , I want and plan include this package on Fedora proper
